CREATE OR ALTER PROCEDURE CreateUsers
As 
	CREATE TABLE Users (
	ID INT PRIMARY KEY IDENTITY(0, 1),
	[First Name] NVARCHAR(50) NOT NULL,
	[Last Name] NVARCHAR(50) NOT NULL,
	Birthdate DATE NOT NULL
)
GO